// auto generated by c2z
const std = @import("std");
//const cpp = @import("cpp");

pub const vec2_t = extern struct {
    x: f32,
    y: f32,
};

extern fn _1_add_(a: vec2_t, b: vec2_t) vec2_t;
pub const add = _1_add_;
