// auto generated by c2z
#include "c002_cpp_structs.h"

extern "C" const vec2_t *_1_vec2_t_sZero_() { return &::vec2_t::sZero; }
extern "C" vec2_t _1_vec2_t_add_(const ::vec2_t *self, vec2_t other) { return self->add(other); }
