// auto generated by c2z
const std = @import("std");
//const cpp = @import("cpp");

pub const vec2_t = extern struct {
    x: f32,
    y: f32,

    extern fn _1_vec2_t_sZero_() *const vec2_t;
    pub inline fn sZero() *const vec2_t {
        return _1_vec2_t_sZero_();
    }

    extern fn _1_vec2_t_add_(self: *const vec2_t, other: vec2_t) vec2_t;
    pub const add = _1_vec2_t_add_;
};

pub const Vec2 = vec2_t;
