// auto generated by c2z
const std = @import("std");
//const cpp = @import("cpp");

pub const Color32 = extern struct {
    mU32: c_uint,
    __field0: extern struct {
        r: u8,
        g: u8,
        b: u8,
        a: u8,
    },
};

pub const ColorClass = extern struct {
    __field0: extern union {
        mU32: c_uint,
        __field0: extern struct {
            r: u8,
            g: u8,
            b: u8,
            a: u8,
        },
    },

    extern fn _1_ColorClass_sBlack_() *const ColorClass;
    pub inline fn sBlack() *const ColorClass {
        return _1_ColorClass_sBlack_();
    }

    extern fn _1_ColorClass_sWhite_() *const ColorClass;
    pub inline fn sWhite() *const ColorClass {
        return _1_ColorClass_sWhite_();
    }
};
