// auto generated by c2z
const std = @import("std");
//const cpp = @import("cpp");

pub const vec2_t = extern struct {
    x: f32,
    y: f32,
};

pub const shape_t = extern struct {
    vtable: *const anyopaque,

    aabb: vec2_t,

    extern fn _1_shape_t_area_(self: *const shape_t) f32;
    pub const area = _1_shape_t_area_;
};

pub const circle_t = extern struct {
    base: shape_t,

    radius: f32,

    extern fn _1_circle_t_init_() circle_t;
    pub const init = _1_circle_t_init_;

    extern fn _2_circle_t_init_(radius: f32) circle_t;
    pub const initRadius = _2_circle_t_init_;

    extern fn _1_circle_t_deinit_(self: *circle_t) void;
    pub const deinit = _1_circle_t_deinit_;

    extern fn _1_circle_t_area_(self: *const circle_t) f32;
    pub const area = _1_circle_t_area_;
};

extern fn _1_area_(shape: *const shape_t) f32;
pub const area = _1_area_;
