// auto generated by c2z
#include "c022_cpp_string.h"

extern "C" std::string _1_get_str_() { return ::get_str(); }
extern "C" bool _1_write_numbers_(std::string & output, size_t count) { return ::write_numbers(output, count); }
