// auto generated by c2z
#include "imgui_impl_opengl3.h"

extern "C" bool _1_ImGui_ImplOpenGL3_Init_(const char * glsl_version) { return ::ImGui_ImplOpenGL3_Init(glsl_version); }
extern "C" void _1_ImGui_ImplOpenGL3_Shutdown_() { ::ImGui_ImplOpenGL3_Shutdown(); }
extern "C" void _1_ImGui_ImplOpenGL3_NewFrame_() { ::ImGui_ImplOpenGL3_NewFrame(); }
extern "C" void _1_ImGui_ImplOpenGL3_RenderDrawData_(ImDrawData * draw_data) { ::ImGui_ImplOpenGL3_RenderDrawData(draw_data); }
extern "C" bool _1_ImGui_ImplOpenGL3_CreateFontsTexture_() { return ::ImGui_ImplOpenGL3_CreateFontsTexture(); }
extern "C" void _1_ImGui_ImplOpenGL3_DestroyFontsTexture_() { ::ImGui_ImplOpenGL3_DestroyFontsTexture(); }
extern "C" bool _1_ImGui_ImplOpenGL3_CreateDeviceObjects_() { return ::ImGui_ImplOpenGL3_CreateDeviceObjects(); }
extern "C" void _1_ImGui_ImplOpenGL3_DestroyDeviceObjects_() { ::ImGui_ImplOpenGL3_DestroyDeviceObjects(); }
