// auto generated by c2z
const std = @import("std");
//const cpp = @import("cpp");

extern fn _1_ImGui_ImplSDL2_Init_(window: *SDL_Window, renderer: [*c]SDL_Renderer, sdl_gl_context: ?*anyopaque) bool;
pub const Init = _1_ImGui_ImplSDL2_Init_;

extern fn _1_ImGui_ImplSDL2_InitForOpenGL_(window: *SDL_Window, sdl_gl_context: ?*anyopaque) bool;
pub const InitForOpenGL = _1_ImGui_ImplSDL2_InitForOpenGL_;

extern fn _1_ImGui_ImplSDL2_InitForVulkan_(window: *SDL_Window) bool;
pub const InitForVulkan = _1_ImGui_ImplSDL2_InitForVulkan_;

extern fn _1_ImGui_ImplSDL2_InitForD3D_(window: *SDL_Window) bool;
pub const InitForD3D = _1_ImGui_ImplSDL2_InitForD3D_;

extern fn _1_ImGui_ImplSDL2_InitForMetal_(window: *SDL_Window) bool;
pub const InitForMetal = _1_ImGui_ImplSDL2_InitForMetal_;

extern fn _1_ImGui_ImplSDL2_InitForSDLRenderer_(window: [*c]SDL_Window, renderer: [*c]SDL_Renderer) bool;
pub const InitForSDLRenderer = _1_ImGui_ImplSDL2_InitForSDLRenderer_;

extern fn _1_ImGui_ImplSDL2_Shutdown_() void;
pub const Shutdown = _1_ImGui_ImplSDL2_Shutdown_;

extern fn _1_ImGui_ImplSDL2_NewFrame_() void;
pub const NewFrame = _1_ImGui_ImplSDL2_NewFrame_;

extern fn _1_ImGui_ImplSDL2_ProcessEvent_(event: [*c]const SDL_Event) bool;
pub const ProcessEvent = _1_ImGui_ImplSDL2_ProcessEvent_;

// opaques

const SDL_Window = anyopaque;
const SDL_Renderer = anyopaque;
const SDL_Event = anyopaque;
