// auto generated by c2z
#include "imgui_impl_sdl2.h"

extern "C" bool _1_ImGui_ImplSDL2_Init_(SDL_Window * window, SDL_Renderer * renderer, void * sdl_gl_context) { return ::ImGui_ImplSDL2_Init(window, renderer, sdl_gl_context); }
extern "C" bool _1_ImGui_ImplSDL2_InitForOpenGL_(SDL_Window * window, void * sdl_gl_context) { return ::ImGui_ImplSDL2_InitForOpenGL(window, sdl_gl_context); }
extern "C" bool _1_ImGui_ImplSDL2_InitForVulkan_(SDL_Window * window) { return ::ImGui_ImplSDL2_InitForVulkan(window); }
extern "C" bool _1_ImGui_ImplSDL2_InitForD3D_(SDL_Window * window) { return ::ImGui_ImplSDL2_InitForD3D(window); }
extern "C" bool _1_ImGui_ImplSDL2_InitForMetal_(SDL_Window * window) { return ::ImGui_ImplSDL2_InitForMetal(window); }
extern "C" bool _1_ImGui_ImplSDL2_InitForSDLRenderer_(SDL_Window * window, SDL_Renderer * renderer) { return ::ImGui_ImplSDL2_InitForSDLRenderer(window, renderer); }
extern "C" void _1_ImGui_ImplSDL2_Shutdown_() { ::ImGui_ImplSDL2_Shutdown(); }
extern "C" void _1_ImGui_ImplSDL2_NewFrame_() { ::ImGui_ImplSDL2_NewFrame(); }
extern "C" bool _1_ImGui_ImplSDL2_ProcessEvent_(const SDL_Event * event) { return ::ImGui_ImplSDL2_ProcessEvent(event); }
