// auto generated by c2z
#include "c003_unions.h"

extern "C" const ColorClass *_1_ColorClass_sBlack_() { return &::ColorClass::sBlack; }
extern "C" const ColorClass *_1_ColorClass_sWhite_() { return &::ColorClass::sWhite; }
