// auto generated by c2z
#include "c005_inheritance.h"

extern "C" float _1_shape_t_area_(const ::shape_t *self) { return self->area(); }
extern "C" ::circle_t _1_circle_t_init_() { return ::circle_t(); }
extern "C" ::circle_t _2_circle_t_init_(float radius) { return ::circle_t(radius); }
extern "C" void _1_circle_t_deinit_(::circle_t *self) { self->~circle_t(); }
extern "C" float _1_circle_t_area_(const ::circle_t *self) { return self->area(); }
extern "C" float _1_area_(const shape_t & shape) { return ::area(shape); }
