// auto generated by c2z
const std = @import("std");
//const cpp = @import("cpp");

extern fn _1_ImAssert_(__arg0: bool) void;
pub const ImAssert = _1_ImAssert_;

pub const ImVec2 = extern struct {
    x: f32,
    y: f32,

    pub fn getPtr(self: *ImVec2, idx: usize) *f32 {
        //ImAssert(idx == 0 or idx == 1);
        return &(@as([*]f32, @ptrCast(self))[idx]);
    }
    pub fn get(self: *const ImVec2, idx: usize) f32 {
        //ImAssert(idx == 0 or idx == 1);
        return @as([*]const f32, @ptrCast(self))[idx];
    }
};
