// auto generated by c2z
#include "c013_cpp_vector.h"

extern "C" std::vector<uint8_t> _1_create_() { return ::create(); }
extern "C" size_t _1_sizeof_vector_uint8_t_() { return ::sizeof_vector_uint8_t(); }
extern "C" const uint8_t * _1_vector_data_(const std::vector<uint8_t> & vec) { return ::vector_data(vec); }
extern "C" size_t _1_vector_size_(const std::vector<uint8_t> & vec) { return ::vector_size(vec); }
extern "C" size_t _1_vector_capacity_(const std::vector<uint8_t> & vec) { return ::vector_capacity(vec); }
extern "C" bool _1_enumerate_(std::vector<uint8_t> & out_buf, size_t count) { return ::enumerate(out_buf, count); }
