// auto generated by c2z
#include "c022_cpp_string.h"

extern "C" int _1_size_of_string_() { return ::size_of_string(); }
extern "C" const char *_1_data_(const std::string &input) { return ::data(input); }
extern "C" const char *_1_cstr_(const std::string &input) { return ::cstr(input); }
extern "C" int _1_cap_(const std::string &input) { return ::cap(input); }
extern "C" std::string _1_get_str_() { return ::get_str(); }
extern "C" bool _1_write_numbers_(std::string &output, size_t count) { return ::write_numbers(output, count); }
