// auto generated by c2z
const std = @import("std");
const cpp = @import("cpp");

extern fn _1_size_of_string_() c_int;
pub const size_of_string = _1_size_of_string_;

extern fn _1_data_(input: *const cpp.String) [*c]const u8;
pub const data = _1_data_;

extern fn _1_cstr_(input: *const cpp.String) [*c]const u8;
pub const cstr = _1_cstr_;

extern fn _1_cap_(input: *const cpp.String) c_int;
pub const cap = _1_cap_;

extern fn _1_get_str_() cpp.String;
pub const get_str = _1_get_str_;

extern fn _1_write_numbers_(output: *cpp.String, count: usize) bool;
pub const write_numbers = _1_write_numbers_;
