// auto generated by c2z
#include <new>
#include "c023_cpp_nested_structs.h"

extern "C" int _1_test_sizeof_RootStruct_() { return ::test_sizeof_RootStruct(); }
extern "C" int _1_test_sizeof_RootUnion_() { return ::test_sizeof_RootUnion(); }
