// auto generated by c2z
const std = @import("std");
//const cpp = @import("cpp");

///
pub extern fn dos_qcoreapplication_application_dir_path() [*c]u8;
///
pub extern fn dos_qcoreapplication_process_events(flags: DosQEventLoopProcessEventFlag) void;
///
pub extern fn dos_qcoreapplication_process_events_timed(flags: DosQEventLoopProcessEventFlag, ms: c_int) void;
///
pub extern fn dos_qguiapplication_create() void;
///
pub extern fn dos_qguiapplication_exec() void;
///
pub extern fn dos_qguiapplication_quit() void;
///
pub extern fn dos_qguiapplication_delete() void;
///
pub extern fn dos_qapplication_create() void;
///
pub extern fn dos_qapplication_exec() void;
///
pub extern fn dos_qapplication_quit() void;
///
pub extern fn dos_qapplication_delete() void;
///
pub extern fn dos_qqmlapplicationengine_create() [*c]DosQQmlApplicationEngine;
///
pub extern fn dos_qqmlapplicationengine_load(vptr: [*c]DosQQmlApplicationEngine, filename: [*c]const u8) void;
///
pub extern fn dos_qqmlapplicationengine_load_url(vptr: [*c]DosQQmlApplicationEngine, url: [*c]DosQUrl) void;
///
pub extern fn dos_qqmlapplicationengine_load_data(vptr: [*c]DosQQmlApplicationEngine, data: [*c]const u8) void;
///
pub extern fn dos_qqmlapplicationengine_add_import_path(vptr: [*c]DosQQmlApplicationEngine, path: [*c]const u8) void;
///
pub extern fn dos_qqmlapplicationengine_context(vptr: [*c]DosQQmlApplicationEngine) [*c]DosQQmlContext;
///
pub extern fn dos_qqmlapplicationengine_addImageProvider(vptr: [*c]DosQQmlApplicationEngine, name: [*c]const u8, vptr_i: [*c]DosQQuickImageProvider) void;
///
pub extern fn dos_qqmlapplicationengine_delete(vptr: [*c]DosQQmlApplicationEngine) void;
///
pub extern fn dos_qquickimageprovider_create(callback: RequestPixmapCallback) [*c]DosQQuickImageProvider;
///
/// Frees a QQuickImageProvider
pub extern fn dos_qquickimageprovider_delete(vptr: [*c]DosQQuickImageProvider) void;
///
pub extern fn dos_qpixmap_create() [*c]DosPixmap;
///
pub extern fn dos_qpixmap_create_qpixmap(other: [*c]const DosPixmap) [*c]DosPixmap;
///
pub extern fn dos_qpixmap_create_width_and_height(width: c_int, height: c_int) [*c]DosPixmap;
///
pub extern fn dos_qpixmap_delete(vptr: [*c]DosPixmap) void;
///
pub extern fn dos_qpixmap_load(vptr: [*c]DosPixmap, filepath: [*c]const u8, format: [*c]const u8) void;
///
pub extern fn dos_qpixmap_loadFromData(vptr: [*c]DosPixmap, data: [*c]const u8, len: c_uint) void;
///
pub extern fn dos_qpixmap_fill(vptr: [*c]DosPixmap, r: u8, g: u8, b: u8, a: u8) void;
///
pub extern fn dos_qpixmap_assign(vptr: [*c]DosPixmap, other: [*c]const DosPixmap) void;
///
pub extern fn dos_qpixmap_isNull(vptr: [*c]DosPixmap) bool;
///
pub extern fn dos_qquickstyle_set_style(style: [*c]const u8) void;
///
pub extern fn dos_qquickstyle_set_fallback_style(style: [*c]const u8) void;
///
pub extern fn dos_qquickview_create() [*c]DosQQuickView;
///
pub extern fn dos_qquickview_show(vptr: [*c]DosQQuickView) void;
///
pub extern fn dos_qquickview_source(vptr: [*c]const DosQQuickView) [*c]u8;
///
pub extern fn dos_qquickview_set_source_url(vptr: [*c]DosQQuickView, url: [*c]DosQUrl) void;
///
pub extern fn dos_qquickview_set_source(vptr: [*c]DosQQuickView, filename: [*c]const u8) void;
///
pub extern fn dos_qquickview_set_resize_mode(vptr: [*c]DosQQuickView, resizeMode: c_int) void;
///
pub extern fn dos_qquickview_delete(vptr: [*c]DosQQuickView) void;
///
pub extern fn dos_qquickview_rootContext(vptr: [*c]DosQQuickView) [*c]DosQQmlContext;
///
pub extern fn dos_qqmlcontext_baseUrl(vptr: [*c]const DosQQmlContext) [*c]u8;
///
pub extern fn dos_qqmlcontext_setcontextproperty(vptr: [*c]DosQQmlContext, name: [*c]const u8, value: [*c]DosQVariant) void;
///
pub extern fn dos_chararray_delete(ptr: [*c]u8) void;
/// Delete a DosQVariantArray
pub extern fn dos_qvariantarray_delete(ptr: [*c]DosQVariantArray) void;
///
pub extern fn dos_qvariant_create() [*c]DosQVariant;
///
pub extern fn dos_qvariant_create_int(value: c_int) [*c]DosQVariant;
///
pub extern fn dos_qvariant_create_longlong(value: c_longlong) [*c]DosQVariant;
///
pub extern fn dos_qvariant_create_ulonglong(value: c_ulonglong) [*c]DosQVariant;
///
pub extern fn dos_qvariant_create_bool(value: bool) [*c]DosQVariant;
///
pub extern fn dos_qvariant_create_string(value: [*c]const u8) [*c]DosQVariant;
///
pub extern fn dos_qvariant_create_qobject(value: [*c]DosQObject) [*c]DosQVariant;
///
pub extern fn dos_qvariant_create_qvariant(value: [*c]const DosQVariant) [*c]DosQVariant;
///
pub extern fn dos_qvariant_create_float(value: f32) [*c]DosQVariant;
///
pub extern fn dos_qvariant_create_double(value: f64) [*c]DosQVariant;
///
pub extern fn dos_qvariant_create_array(size: c_int, array: [*c][*c]DosQVariant) [*c]DosQVariant;
///
pub extern fn dos_qvariant_setInt(vptr: [*c]DosQVariant, value: c_int) void;
///
pub extern fn dos_qvariant_setLongLong(vptr: [*c]DosQVariant, value: c_longlong) void;
///
pub extern fn dos_qvariant_setULongLong(vptr: [*c]DosQVariant, value: c_ulonglong) void;
///
pub extern fn dos_qvariant_setBool(vptr: [*c]DosQVariant, value: bool) void;
///
pub extern fn dos_qvariant_setFloat(vptr: [*c]DosQVariant, value: f32) void;
///
pub extern fn dos_qvariant_setDouble(vptr: [*c]DosQVariant, value: f64) void;
///
pub extern fn dos_qvariant_setString(vptr: [*c]DosQVariant, value: [*c]const u8) void;
///
pub extern fn dos_qvariant_setQObject(vptr: [*c]DosQVariant, value: [*c]DosQObject) void;
///
pub extern fn dos_qvariant_setArray(vptr: [*c]DosQVariant, size: c_int, array: [*c][*c]DosQVariant) void;
///
pub extern fn dos_qvariant_isnull(vptr: [*c]const DosQVariant) bool;
///
pub extern fn dos_qvariant_delete(vptr: [*c]DosQVariant) void;
///
pub extern fn dos_qvariant_assign(vptr: [*c]DosQVariant, other: [*c]const DosQVariant) void;
///
pub extern fn dos_qvariant_toInt(vptr: [*c]const DosQVariant) c_int;
///
pub extern fn dos_qvariant_toLongLong(vptr: [*c]const DosQVariant) c_longlong;
///
pub extern fn dos_qvariant_toULongLong(vptr: [*c]const DosQVariant) c_ulonglong;
///
pub extern fn dos_qvariant_toBool(vptr: [*c]const DosQVariant) bool;
///
pub extern fn dos_qvariant_toString(vptr: [*c]const DosQVariant) [*c]u8;
///
pub extern fn dos_qvariant_toFloat(vptr: [*c]const DosQVariant) f32;
///
pub extern fn dos_qvariant_toDouble(vptr: [*c]const DosQVariant) f64;
///
pub extern fn dos_qvariant_toArray(vptr: [*c]const DosQVariant) [*c]DosQVariantArray;
///
pub extern fn dos_qvariant_toQObject(vptr: [*c]const DosQVariant) [*c]DosQObject;
///
pub extern fn dos_qmetaobject_create(superClassMetaObject: [*c]DosQMetaObject, className: [*c]const u8, signalDefinitions: [*c]const SignalDefinitions, slotDefinitions: [*c]const SlotDefinitions, propertyDefinitions: [*c]const PropertyDefinitions) [*c]DosQMetaObject;
///
pub extern fn dos_qmetaobject_delete(vptr: [*c]DosQMetaObject) void;
///
pub extern fn dos_qmetaobject_invoke_method(context: [*c]DosQObject, callback: DosQMetaObjectInvokeMethodCallback, callbackData: ?*anyopaque, connection_type: DosQtConnectionType) bool;
///
pub extern fn dos_qabstractlistmodel_qmetaobject() [*c]DosQMetaObject;
///
pub extern fn dos_qabstractlistmodel_create(callbackObject: ?*anyopaque, metaObject: [*c]DosQMetaObject, dObjectCallback: DObjectCallback, callbacks: [*c]DosQAbstractItemModelCallbacks) [*c]DosQAbstractListModel;
///
pub extern fn dos_qabstractlistmodel_index(vptr: [*c]DosQAbstractListModel, row: c_int, column: c_int, parent: [*c]DosQModelIndex) [*c]DosQModelIndex;
///
pub extern fn dos_qabstractlistmodel_parent(vptr: [*c]DosQAbstractListModel, child: [*c]DosQModelIndex) [*c]DosQModelIndex;
///
pub extern fn dos_qabstractlistmodel_columnCount(vptr: [*c]DosQAbstractListModel, parent: [*c]DosQModelIndex) c_int;
///
pub extern fn dos_qabstracttablemodel_qmetaobject() [*c]DosQMetaObject;
///
pub extern fn dos_qabstracttablemodel_create(callbackObject: ?*anyopaque, metaObject: [*c]DosQMetaObject, dObjectCallback: DObjectCallback, callbacks: [*c]DosQAbstractItemModelCallbacks) [*c]DosQAbstractTableModel;
///
pub extern fn dos_qabstracttablemodel_index(vptr: [*c]DosQAbstractTableModel, row: c_int, column: c_int, parent: [*c]DosQModelIndex) [*c]DosQModelIndex;
///
pub extern fn dos_qabstracttablemodel_parent(vptr: [*c]DosQAbstractTableModel, child: [*c]DosQModelIndex) [*c]DosQModelIndex;
///
pub extern fn dos_qabstractitemmodel_qmetaobject() [*c]DosQMetaObject;
///
pub extern fn dos_qabstractitemmodel_create(callbackObject: ?*anyopaque, metaObject: [*c]DosQMetaObject, dObjectCallback: DObjectCallback, callbacks: [*c]DosQAbstractItemModelCallbacks) [*c]DosQAbstractItemModel;
///
pub extern fn dos_qabstractitemmodel_setData(vptr: [*c]DosQAbstractItemModel, index: [*c]DosQModelIndex, data: [*c]DosQVariant, role: c_int) bool;
///
pub extern fn dos_qabstractitemmodel_roleNames(vptr: [*c]DosQAbstractItemModel) [*c]DosQHashIntQByteArray;
///
pub extern fn dos_qabstractitemmodel_flags(vptr: [*c]DosQAbstractItemModel, index: [*c]DosQModelIndex) c_int;
///
pub extern fn dos_qabstractitemmodel_headerData(vptr: [*c]DosQAbstractItemModel, section: c_int, orientation: c_int, role: c_int) [*c]DosQVariant;
///
pub extern fn dos_qabstractitemmodel_hasChildren(vptr: [*c]DosQAbstractItemModel, parentIndex: [*c]DosQModelIndex) bool;
///
pub extern fn dos_qabstractitemmodel_hasIndex(vptr: [*c]DosQAbstractItemModel, row: c_int, column: c_int, dosParentIndex: [*c]DosQModelIndex) bool;
///
pub extern fn dos_qabstractitemmodel_canFetchMore(vptr: [*c]DosQAbstractItemModel, parentIndex: [*c]DosQModelIndex) bool;
///
pub extern fn dos_qabstractitemmodel_fetchMore(vptr: [*c]DosQAbstractItemModel, parentIndex: [*c]DosQModelIndex) void;
///
pub extern fn dos_qabstractitemmodel_beginInsertRows(vptr: [*c]DosQAbstractItemModel, parent: [*c]DosQModelIndex, first: c_int, last: c_int) void;
///
pub extern fn dos_qabstractitemmodel_endInsertRows(vptr: [*c]DosQAbstractItemModel) void;
///
pub extern fn dos_qabstractitemmodel_beginRemoveRows(vptr: [*c]DosQAbstractItemModel, parent: [*c]DosQModelIndex, first: c_int, last: c_int) void;
///
pub extern fn dos_qabstractitemmodel_endRemoveRows(vptr: [*c]DosQAbstractItemModel) void;
///
pub extern fn dos_qabstractitemmodel_beginInsertColumns(vptr: [*c]DosQAbstractItemModel, parent: [*c]DosQModelIndex, first: c_int, last: c_int) void;
///
pub extern fn dos_qabstractitemmodel_endInsertColumns(vptr: [*c]DosQAbstractItemModel) void;
///
pub extern fn dos_qabstractitemmodel_beginRemoveColumns(vptr: [*c]DosQAbstractItemModel, parent: [*c]DosQModelIndex, first: c_int, last: c_int) void;
///
pub extern fn dos_qabstractitemmodel_endRemoveColumns(vptr: [*c]DosQAbstractItemModel) void;
///
pub extern fn dos_qabstractitemmodel_beginResetModel(vptr: [*c]DosQAbstractItemModel) void;
///
pub extern fn dos_qabstractitemmodel_endResetModel(vptr: [*c]DosQAbstractItemModel) void;
///
pub extern fn dos_qabstractitemmodel_dataChanged(vptr: [*c]DosQAbstractItemModel, topLeft: [*c]const DosQModelIndex, bottomRight: [*c]const DosQModelIndex, rolesPtr: [*c]c_int, rolesLength: c_int) void;
///
pub extern fn dos_qabstractitemmodel_createIndex(vptr: [*c]DosQAbstractItemModel, row: c_int, column: c_int, data: ?*anyopaque) [*c]DosQModelIndex;
///
pub extern fn dos_qabstractitemmodel_setData(vptr: [*c]DosQAbstractItemModel, index: [*c]DosQModelIndex, value: [*c]DosQVariant, role: c_int) bool;
///
pub extern fn dos_qabstractitemmodel_roleNames(vptr: [*c]DosQAbstractItemModel) [*c]DosQHashIntQByteArray;
///
pub extern fn dos_qabstractitemmodel_flags(vptr: [*c]DosQAbstractItemModel, index: [*c]DosQModelIndex) c_int;
///
pub extern fn dos_qabstractitemmodel_headerData(vptr: [*c]DosQAbstractItemModel, section: c_int, orientation: c_int, role: c_int) [*c]DosQVariant;
///
pub extern fn dos_qobject_qmetaobject() [*c]DosQMetaObject;
///
pub extern fn dos_qobject_create(dObjectPointer: ?*anyopaque, metaObject: [*c]DosQMetaObject, dObjectCallback: DObjectCallback) [*c]DosQObject;
///
pub extern fn dos_qobject_signal_emit(vptr: [*c]DosQObject, name: [*c]const u8, parametersCount: c_int, parameters: [*c]?*anyopaque) void;
///
pub extern fn dos_qobject_objectName(vptr: [*c]const DosQObject) [*c]u8;
///
pub extern fn dos_qobject_setObjectName(vptr: [*c]DosQObject, name: [*c]const u8) void;
///
pub extern fn dos_qobject_delete(vptr: [*c]DosQObject) void;
///
pub extern fn dos_qobject_deleteLater(vptr: [*c]DosQObject) void;
///
pub extern fn dos_qobject_property(vptr: [*c]DosQObject, propertyName: [*c]const u8) [*c]DosQVariant;
///
pub extern fn dos_qobject_setProperty(vptr: [*c]DosQObject, propertyName: [*c]const u8, value: [*c]DosQVariant) bool;
///
pub extern fn dos_slot_macro(str: [*c]const u8) [*c]u8;
///
pub extern fn dos_signal_macro(str: [*c]const u8) [*c]u8;
///
pub extern fn dos_qobject_connect_lambda_static(sender: [*c]DosQObject, signal: [*c]const u8, callback: DosQObjectConnectLambdaCallback, callbackData: ?*anyopaque, connection_type: DosQtConnectionType) [*c]DosQMetaObjectConnection;
///
pub extern fn dos_qobject_connect_lambda_with_context_static(sender: [*c]DosQObject, signal: [*c]const u8, context: [*c]DosQObject, callback: DosQObjectConnectLambdaCallback, callbackData: ?*anyopaque, connection_type: DosQtConnectionType) [*c]DosQMetaObjectConnection;
///
pub extern fn dos_qobject_connect_static(sender: [*c]DosQObject, signal: [*c]const u8, receiver: [*c]DosQObject, slot: [*c]const u8, connection_type: DosQtConnectionType) [*c]DosQMetaObjectConnection;
///
pub extern fn dos_qobject_disconnect_static(sender: [*c]DosQObject, signal: [*c]const u8, receiver: [*c]DosQObject, slot: [*c]const u8) void;
///
pub extern fn dos_qobject_disconnect_with_connection_static(connection: [*c]DosQMetaObjectConnection) void;
///
///
pub extern fn dos_qmetaobject_connection_delete(self: [*c]DosQMetaObjectConnection) void;
///
pub extern fn dos_qmodelindex_create() [*c]DosQModelIndex;
///
pub extern fn dos_qmodelindex_create_qmodelindex(index: [*c]DosQModelIndex) [*c]DosQModelIndex;
///
pub extern fn dos_qmodelindex_delete(vptr: [*c]DosQModelIndex) void;
///
pub extern fn dos_qmodelindex_row(vptr: [*c]const DosQModelIndex) c_int;
///
pub extern fn dos_qmodelindex_column(vptr: [*c]const DosQModelIndex) c_int;
///
pub extern fn dos_qmodelindex_isValid(vptr: [*c]const DosQModelIndex) bool;
///
pub extern fn dos_qmodelindex_data(vptr: [*c]const DosQModelIndex, role: c_int) [*c]DosQVariant;
///
pub extern fn dos_qmodelindex_parent(vptr: [*c]const DosQModelIndex) [*c]DosQModelIndex;
///
pub extern fn dos_qmodelindex_child(vptr: [*c]const DosQModelIndex, row: c_int, column: c_int) [*c]DosQModelIndex;
///
pub extern fn dos_qmodelindex_sibling(vptr: [*c]const DosQModelIndex, row: c_int, column: c_int) [*c]DosQModelIndex;
///
pub extern fn dos_qmodelindex_assign(l: [*c]DosQModelIndex, r: [*c]const DosQModelIndex) void;
///
pub extern fn dos_qmodelindex_internalPointer(vptr: [*c]DosQModelIndex) ?*anyopaque;
///
pub extern fn dos_qhash_int_qbytearray_create() [*c]DosQHashIntQByteArray;
///
pub extern fn dos_qhash_int_qbytearray_delete(vptr: [*c]DosQHashIntQByteArray) void;
///
pub extern fn dos_qhash_int_qbytearray_insert(vptr: [*c]DosQHashIntQByteArray, key: c_int, value: [*c]const u8) void;
///
pub extern fn dos_qhash_int_qbytearray_value(vptr: [*c]const DosQHashIntQByteArray, key: c_int) [*c]u8;
/// Register the given .rcc (compiled) file in the resource system
pub extern fn dos_qresource_register(filename: [*c]const u8) void;
///
pub extern fn dos_qurl_create(url: [*c]const u8, parsingMode: c_int) [*c]DosQUrl;
///
pub extern fn dos_qurl_delete(vptr: [*c]DosQUrl) void;
///
pub extern fn dos_qurl_to_string(vptr: [*c]const DosQUrl) [*c]u8;
///
pub extern fn dos_qurl_isValid(vptr: [*c]const DosQUrl) bool;
///
pub extern fn dos_qdeclarative_qmlregistertype(qmlRegisterType: [*c]const QmlRegisterType) c_int;
///
pub extern fn dos_qdeclarative_qmlregistersingletontype(qmlRegisterType: [*c]const QmlRegisterType) c_int;
///
pub extern fn dos_qpointer_create(object: [*c]DosQObject) [*c]DosQPointer;
///
pub extern fn dos_qpointer_delete(self: [*c]DosQPointer) void;
///
pub extern fn dos_qpointer_is_null(self: [*c]DosQPointer) bool;
///
pub extern fn dos_qpointer_clear(self: [*c]DosQPointer) void;
///
pub extern fn dos_qpointer_data(self: [*c]DosQPointer) [*c]DosQObject;
